#!/usr/bin/env python

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=[
    "src",
    "../../core/include"
])

sources = Glob("src/*.cpp")
sources += Glob("../../core/src/*.cpp")

library = env.SharedLibrary(
    target="../bin/climb_core",
    source=sources
)

Default(library)